services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://LeelaShiv7275:Leela%40Shiv72757275@cluster0.bz5da.mongodb.net/chatfun
      - JWT_SECRET=1de2977917e9e33dfe2e79f5a273458b910f4bfe551b6d86120705ab3e0092fd
      - EMAIL_USER=kingravin001@gmail.com
      - EMAIL_PASS=lwbg biio gjpu fcfp
      - REDIS_URL=redis://red-cvgr815umphs73cv5hl0:6379
      - RABBITMQ_URL=amqp://guest:guest@chatfun-backend.onrender.com:5672

    depends_on:
      - rabbitmq
      - redis
    networks:
      - server_default

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - server_default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - server_default

networks:
  server_default:
    external: true
